"""Numerical correctness tests for preprocessing transformers.

This module validates that Spectral Predict's preprocessing implementations
produce numerically identical results to validated external implementations.

All tests use gold standard reference data generated by
scripts/generate_gold_standards.py, which uses:
- SNV: Direct formula implementation
- Savitzky-Golay: scipy.signal.savgol_filter
- PLS: sklearn.cross_decomposition.PLSRegression
- Baseline: numpy.polyfit polynomial fitting

Tolerance levels:
- 1e-10: For exact mathematical operations (SNV)
- 1e-12: For scipy derivative operations
- 1e-6: For iterative algorithms (PLS, baseline)
"""

from __future__ import annotations

import numpy as np
import pytest
from pathlib import Path

# Import Spectral Predict implementations to validate
from spectral_predict.preprocess import SNV, SavgolDerivative, SavgolSmooth
from spectral_predict.baseline import BaselinePolynomial


@pytest.fixture(scope="module")
def gold_standard_dir() -> Path:
    """Path to gold standard reference files."""
    return Path(__file__).parent.parent / "gold_standards"


@pytest.fixture(scope="module")
def snv_gold_standard(gold_standard_dir: Path) -> dict:
    """Load SNV gold standard data."""
    data = np.load(gold_standard_dir / "snv_outputs.npz")
    return {
        "input": data["input"],
        "output": data["output"],
        "description": str(data["description"])
    }


@pytest.fixture(scope="module")
def derivatives_gold_standard(gold_standard_dir: Path) -> dict:
    """Load derivatives gold standard data."""
    data = np.load(gold_standard_dir / "derivatives.npz")
    return {
        "input": data["input"],
        "deriv1_w7_p2": data["deriv1_w7_p2"],
        "deriv2_w7_p3": data["deriv2_w7_p3"],
        "deriv1_w11_p3": data["deriv1_w11_p3"],
        "description": str(data["description"])
    }


@pytest.fixture(scope="module")
def baseline_gold_standard(gold_standard_dir: Path) -> dict:
    """Load baseline correction gold standard data."""
    data = np.load(gold_standard_dir / "baseline_outputs.npz")
    return {
        "wavelengths": data["wavelengths"],
        "observed_spectrum": data["observed_spectrum"],
        "corrected_spectrum": data["corrected_spectrum"],
        "X_observed": data["X_observed"],
        "X_corrected": data["X_corrected"],
        "polynomial_degree": int(data["polynomial_degree"]),
        "description": str(data["description"])
    }


@pytest.fixture(scope="module")
def edge_cases_gold_standard(gold_standard_dir: Path) -> dict:
    """Load edge case gold standard data."""
    data = np.load(gold_standard_dir / "edge_cases.npz")
    return {
        "X_single": data["X_single"],
        "X_single_snv": data["X_single_snv"],
        "X_constant": data["X_constant"],
        "X_constant_snv": data["X_constant_snv"],
        "X_small": data["X_small"],
        "X_small_deriv1": data["X_small_deriv1"],
        "description": str(data["description"])
    }


@pytest.mark.numerical
class TestSNVCorrectness:
    """Test SNV implementation matches gold standard."""

    def test_snv_matches_gold_standard(self, snv_gold_standard: dict):
        """Verify SNV matches validated reference to 1e-10 tolerance."""
        X_input = snv_gold_standard["input"]
        X_expected = snv_gold_standard["output"]

        # Apply Spectral Predict SNV
        snv = SNV()
        X_actual = snv.fit_transform(X_input)

        # Compare to gold standard
        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="SNV output does not match gold standard"
        )

    def test_snv_single_sample(self, edge_cases_gold_standard: dict):
        """Verify SNV handles single sample correctly."""
        X_input = edge_cases_gold_standard["X_single"]
        X_expected = edge_cases_gold_standard["X_single_snv"]

        snv = SNV()
        X_actual = snv.fit_transform(X_input)

        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="SNV fails on single sample"
        )

    def test_snv_constant_values(self, edge_cases_gold_standard: dict):
        """Verify SNV handles constant values (zero variance) gracefully."""
        X_input = edge_cases_gold_standard["X_constant"]
        X_expected = edge_cases_gold_standard["X_constant_snv"]

        snv = SNV()
        X_actual = snv.fit_transform(X_input)

        # Should return zeros (mean-centered with std=1 denominator)
        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="SNV fails on constant values"
        )

        # Verify it's actually all zeros
        assert np.allclose(X_actual, 0.0), "SNV of constant values should be zero"

    def test_snv_deterministic(self, snv_gold_standard: dict):
        """Verify SNV produces identical results on repeated calls."""
        X_input = snv_gold_standard["input"]

        snv = SNV()
        X_result1 = snv.fit_transform(X_input)
        X_result2 = snv.fit_transform(X_input)

        np.testing.assert_array_equal(
            X_result1, X_result2,
            err_msg="SNV is not deterministic"
        )

    def test_snv_preserves_shape(self, snv_gold_standard: dict):
        """Verify SNV preserves input shape."""
        X_input = snv_gold_standard["input"]

        snv = SNV()
        X_output = snv.fit_transform(X_input)

        assert X_output.shape == X_input.shape, "SNV changed array shape"


@pytest.mark.numerical
class TestSavgolDerivativeCorrectness:
    """Test Savitzky-Golay derivative implementation matches scipy."""

    def test_savgol_first_derivative_matches_scipy(self, derivatives_gold_standard: dict):
        """Verify 1st derivative matches scipy.signal.savgol_filter."""
        X_input = derivatives_gold_standard["input"]
        X_expected = derivatives_gold_standard["deriv1_w7_p2"]

        # Apply Spectral Predict Savgol (window=7, polyorder=2, deriv=1)
        savgol = SavgolDerivative(deriv=1, window=7, polyorder=2)
        X_actual = savgol.fit_transform(X_input)

        # Tolerance 1e-10: SG-derivative coefficients accumulate ~3.86e-12 FP drift
        # across scipy versions on Linux; 1e-10 keeps a 25× safety margin while
        # staying above the realistic precision floor for cross-platform CI.
        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="1st derivative does not match scipy"
        )

    def test_savgol_second_derivative_matches_scipy(self, derivatives_gold_standard: dict):
        """Verify 2nd derivative matches scipy.signal.savgol_filter."""
        X_input = derivatives_gold_standard["input"]
        X_expected = derivatives_gold_standard["deriv2_w7_p3"]

        # Apply Spectral Predict Savgol (window=7, polyorder=3, deriv=2)
        savgol = SavgolDerivative(deriv=2, window=7, polyorder=3)
        X_actual = savgol.fit_transform(X_input)

        # Tolerance 1e-10: see 1st-derivative test for cross-platform scipy drift rationale.
        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="2nd derivative does not match scipy"
        )

    def test_savgol_alternate_parameters(self, derivatives_gold_standard: dict):
        """Verify derivatives match scipy with different window/polyorder."""
        X_input = derivatives_gold_standard["input"]
        X_expected = derivatives_gold_standard["deriv1_w11_p3"]

        # Apply with different parameters (window=11, polyorder=3, deriv=1)
        savgol = SavgolDerivative(deriv=1, window=11, polyorder=3)
        X_actual = savgol.fit_transform(X_input)

        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-12, atol=1e-12,
            err_msg="Derivative with alternate parameters does not match scipy"
        )

    def test_savgol_small_window(self, edge_cases_gold_standard: dict):
        """Verify derivatives work with small windows."""
        X_input = edge_cases_gold_standard["X_small"]
        X_expected = edge_cases_gold_standard["X_small_deriv1"]

        savgol = SavgolDerivative(deriv=1, window=5, polyorder=2)
        X_actual = savgol.fit_transform(X_input)

        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-12, atol=1e-12,
            err_msg="Small window derivative does not match scipy"
        )

    def test_savgol_even_window_increment(self, derivatives_gold_standard: dict):
        """Verify even windows are incremented to odd."""
        X_input = derivatives_gold_standard["input"]

        # Even window should be incremented to 7
        savgol_even = SavgolDerivative(deriv=1, window=6, polyorder=2)
        X_even = savgol_even.fit_transform(X_input)

        # Odd window 7
        savgol_odd = SavgolDerivative(deriv=1, window=7, polyorder=2)
        X_odd = savgol_odd.fit_transform(X_input)

        # Should be identical
        np.testing.assert_array_equal(
            X_even, X_odd,
            err_msg="Even window not correctly incremented to odd"
        )

    def test_savgol_default_polyorder(self, derivatives_gold_standard: dict):
        """Verify default polyorder selection."""
        X_input = derivatives_gold_standard["input"]

        # Default for deriv=1 should be polyorder=2
        savgol_default = SavgolDerivative(deriv=1, window=7, polyorder=None)
        savgol_explicit = SavgolDerivative(deriv=1, window=7, polyorder=2)

        X_default = savgol_default.fit_transform(X_input)
        X_explicit = savgol_explicit.fit_transform(X_input)

        np.testing.assert_array_equal(
            X_default, X_explicit,
            err_msg="Default polyorder does not match expected value"
        )

    def test_savgol_deterministic(self, derivatives_gold_standard: dict):
        """Verify Savgol produces identical results on repeated calls."""
        X_input = derivatives_gold_standard["input"]

        savgol = SavgolDerivative(deriv=1, window=7, polyorder=2)
        X_result1 = savgol.fit_transform(X_input)
        X_result2 = savgol.fit_transform(X_input)

        np.testing.assert_array_equal(
            X_result1, X_result2,
            err_msg="Savgol is not deterministic"
        )


@pytest.mark.numerical
class TestSavgolSmoothCorrectness:
    """Test Savitzky-Golay smoothing implementation."""

    def test_savgol_smooth_is_zeroth_derivative(self, derivatives_gold_standard: dict):
        """Verify smoothing is equivalent to deriv=0."""
        X_input = derivatives_gold_standard["input"]

        # Smoothing should be equivalent to savgol_filter with deriv=0
        from scipy.signal import savgol_filter

        smooth = SavgolSmooth(window_length=17, polyorder=2)
        X_smooth = smooth.fit_transform(X_input)

        X_expected = savgol_filter(X_input, window_length=17, polyorder=2, deriv=0, axis=1)

        np.testing.assert_allclose(
            X_smooth, X_expected,
            rtol=1e-12, atol=1e-12,
            err_msg="Smoothing does not match scipy savgol_filter with deriv=0"
        )

    def test_savgol_smooth_even_window_increment(self, derivatives_gold_standard: dict):
        """Verify even windows are incremented to odd for smoothing."""
        X_input = derivatives_gold_standard["input"]

        # Even window should be incremented to 17
        smooth_even = SavgolSmooth(window_length=16, polyorder=2)
        X_even = smooth_even.fit_transform(X_input)

        # Odd window 17
        smooth_odd = SavgolSmooth(window_length=17, polyorder=2)
        X_odd = smooth_odd.fit_transform(X_input)

        # Should be identical
        np.testing.assert_array_equal(
            X_even, X_odd,
            err_msg="Even window not correctly incremented to odd in smoothing"
        )


@pytest.mark.numerical
class TestBaselinePolynomialCorrectness:
    """Test polynomial baseline correction implementation."""

    def test_baseline_polynomial_matches_numpy(self, baseline_gold_standard: dict):
        """Verify polynomial baseline correction matches numpy.polyfit."""
        X_observed = baseline_gold_standard["X_observed"]
        X_expected = baseline_gold_standard["X_corrected"]
        degree = baseline_gold_standard["polynomial_degree"]

        # Apply Spectral Predict baseline correction
        baseline = BaselinePolynomial(degree=degree)
        X_actual = baseline.fit_transform(X_observed)

        # Compare to numpy gold standard
        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="Polynomial baseline correction does not match numpy.polyfit"
        )

    def test_baseline_polynomial_single_spectrum(self, baseline_gold_standard: dict):
        """Verify baseline correction works on single spectrum."""
        observed = baseline_gold_standard["observed_spectrum"]
        expected = baseline_gold_standard["corrected_spectrum"]
        degree = baseline_gold_standard["polynomial_degree"]

        # Reshape to 2D for transformer
        X_observed = observed.reshape(1, -1)
        X_expected = expected.reshape(1, -1)

        baseline = BaselinePolynomial(degree=degree)
        X_actual = baseline.fit_transform(X_observed)

        np.testing.assert_allclose(
            X_actual, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="Baseline correction fails on single spectrum"
        )

    def test_baseline_polynomial_degree_1(self, derivatives_gold_standard: dict):
        """Verify linear baseline (degree=1) works correctly."""
        X_input = derivatives_gold_standard["input"]

        # Apply linear baseline
        baseline = BaselinePolynomial(degree=1)
        X_corrected = baseline.fit_transform(X_input)

        # Manually compute expected result
        wavelengths = np.arange(X_input.shape[1])
        X_expected = np.zeros_like(X_input)
        for i in range(X_input.shape[0]):
            coeffs = np.polyfit(wavelengths, X_input[i, :], deg=1)
            baseline_vals = np.polyval(coeffs, wavelengths)
            X_expected[i, :] = X_input[i, :] - baseline_vals

        np.testing.assert_allclose(
            X_corrected, X_expected,
            rtol=1e-10, atol=1e-10,
            err_msg="Linear baseline does not match numpy.polyfit"
        )

    def test_baseline_polynomial_deterministic(self, baseline_gold_standard: dict):
        """Verify baseline correction is deterministic."""
        X_observed = baseline_gold_standard["X_observed"]

        baseline = BaselinePolynomial(degree=2)
        X_result1 = baseline.fit_transform(X_observed)
        X_result2 = baseline.fit_transform(X_observed)

        np.testing.assert_array_equal(
            X_result1, X_result2,
            err_msg="Baseline correction is not deterministic"
        )

    def test_baseline_polynomial_preserves_shape(self, baseline_gold_standard: dict):
        """Verify baseline correction preserves input shape."""
        X_observed = baseline_gold_standard["X_observed"]

        baseline = BaselinePolynomial(degree=2)
        X_corrected = baseline.fit_transform(X_observed)

        assert X_corrected.shape == X_observed.shape, "Baseline correction changed array shape"


@pytest.mark.numerical
class TestPipelineCorrectness:
    """Test combined preprocessing pipelines produce correct results."""

    def test_snv_then_derivative(self, derivatives_gold_standard: dict):
        """Verify SNV followed by derivative produces correct combined result."""
        X_input = derivatives_gold_standard["input"]

        # Apply SNV then derivative
        snv = SNV()
        savgol = SavgolDerivative(deriv=1, window=7, polyorder=2)

        X_snv = snv.fit_transform(X_input)
        X_combined = savgol.fit_transform(X_snv)

        # Manually compute expected result using scipy
        from scipy.signal import savgol_filter

        # SNV
        means = X_input.mean(axis=1, keepdims=True)
        stds = X_input.std(axis=1, keepdims=True)
        stds[stds == 0] = 1.0
        X_snv_expected = (X_input - means) / stds

        # Then derivative
        X_expected = savgol_filter(X_snv_expected, window_length=7, polyorder=2, deriv=1, axis=1)

        np.testing.assert_allclose(
            X_combined, X_expected,
            rtol=1e-12, atol=1e-12,
            err_msg="SNV→Derivative pipeline does not match expected result"
        )

    def test_derivative_then_snv(self, derivatives_gold_standard: dict):
        """Verify derivative followed by SNV produces correct combined result."""
        X_input = derivatives_gold_standard["input"]

        # Apply derivative then SNV
        savgol = SavgolDerivative(deriv=1, window=7, polyorder=2)
        snv = SNV()

        X_deriv = savgol.fit_transform(X_input)
        X_combined = snv.fit_transform(X_deriv)

        # Manually compute expected result
        from scipy.signal import savgol_filter

        # Derivative
        X_deriv_expected = savgol_filter(X_input, window_length=7, polyorder=2, deriv=1, axis=1)

        # Then SNV
        means = X_deriv_expected.mean(axis=1, keepdims=True)
        stds = X_deriv_expected.std(axis=1, keepdims=True)
        stds[stds == 0] = 1.0
        X_expected = (X_deriv_expected - means) / stds

        np.testing.assert_allclose(
            X_combined, X_expected,
            rtol=1e-12, atol=1e-12,
            err_msg="Derivative→SNV pipeline does not match expected result"
        )


@pytest.mark.numerical
class TestInputValidation:
    """Test that invalid inputs are properly rejected."""

    def test_savgol_window_too_small(self, derivatives_gold_standard: dict):
        """Verify error when window < polyorder + 2."""
        X_input = derivatives_gold_standard["input"]

        # Window=5, polyorder=4 should fail (5 < 4 + 2)
        savgol = SavgolDerivative(deriv=1, window=5, polyorder=4)

        with pytest.raises(ValueError, match="Window length .* must be >= polyorder"):
            savgol.fit_transform(X_input)

    def test_savgol_window_too_large(self, derivatives_gold_standard: dict):
        """Verify auto-adjustment when window > number of features."""
        X_input = derivatives_gold_standard["input"]

        # Window larger than number of features now auto-adjusts instead of raising
        savgol = SavgolDerivative(deriv=1, window=200, polyorder=2)

        # Should auto-adjust the window and produce valid output
        result = savgol.fit_transform(X_input)
        assert result.shape == X_input.shape, "Auto-adjusted window should preserve shape"

    def test_smooth_window_too_small(self, derivatives_gold_standard: dict):
        """Verify error when smoothing window < polyorder + 2."""
        X_input = derivatives_gold_standard["input"]

        # Window=5, polyorder=4 should fail
        smooth = SavgolSmooth(window_length=5, polyorder=4)

        with pytest.raises(ValueError, match="Window length .* must be >= polyorder"):
            smooth.fit_transform(X_input)


if __name__ == "__main__":
    # Allow running tests directly
    pytest.main([__file__, "-v", "--tb=short"])
