"""
ZIP bundle exporter for complete analysis packages.

Creates a complete project bundle with Python scripts, R scripts,
Jupyter notebooks, data files, and documentation.
"""

import os
import json
import zipfile
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional
import numpy as np
import pandas as pd

from .code_generator import CodeGenerator, ExportOptions
from .r_code_generator import RCodeGenerator


class ExportBundle:
    """
    Create a complete ZIP bundle with Python, R, and data files.

    Parameters
    ----------
    model_config : dict
        Model configuration dictionary
    output_path : str
        Path for the output ZIP file
    include_data : bool
        Include actual data files
    data_X : np.ndarray, optional
        Spectral data
    data_y : np.ndarray, optional
        Target values
    wavelengths : np.ndarray, optional
        Wavelength array
    """

    def __init__(
        self,
        model_config: Dict[str, Any],
        output_path: str,
        include_data: bool = True,
        data_X: Optional[np.ndarray] = None,
        data_y: Optional[np.ndarray] = None,
        wavelengths: Optional[np.ndarray] = None
    ):
        self.config = model_config
        self.output_path = output_path
        self.include_data = include_data
        self.data_X = data_X
        self.data_y = data_y
        self.wavelengths = wavelengths

        # Extract model info
        self.model_name = model_config.get('model_name', 'Unknown')
        self.preprocessing = model_config.get('preprocessing', 'raw')
        self.task_type = model_config.get('task_type', 'regression')

    def create_bundle(self):
        """
        Create the complete export bundle.

        Creates a ZIP file with the following structure:
        analysis_export_YYYY-MM-DD/
        ├── README.md
        ├── python/
        │   ├── analysis.py
        │   ├── analysis.ipynb
        │   └── requirements.txt
        ├── r/
        │   ├── analysis.R
        │   └── install_packages.R
        └── data/
            ├── spectra.csv
            ├── target.csv
            └── wavelengths.csv
        """
        timestamp = datetime.now().strftime('%Y-%m-%d')
        bundle_name = f"analysis_export_{timestamp}"

        with zipfile.ZipFile(self.output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            # 1. README
            readme_content = self._generate_readme()
            zipf.writestr(f"{bundle_name}/README.md", readme_content)

            # 2. Python files
            self._add_python_files(zipf, bundle_name)

            # 3. R files
            self._add_r_files(zipf, bundle_name)

            # 4. Data files (if requested)
            if self.include_data and self.data_X is not None:
                self._add_data_files(zipf, bundle_name)

        return self.output_path

    def _generate_readme(self) -> str:
        """Generate README.md for the bundle."""
        readme = f"""# Spectral Analysis Export

Generated by Spectral Predict on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Model Information

- **Model**: {self.model_name}
- **Preprocessing**: {self.preprocessing}
- **Task Type**: {self.task_type}
- **CV Folds**: {self.config.get('cv_folds', 5)}

## Model Parameters

"""
        params = self.config.get('params', {})
        if params:
            for key, value in params.items():
                readme += f"- `{key}`: {value}\n"
        else:
            readme += "- Default parameters\n"

        readme += f"""
## Performance Metrics

"""
        metrics = self.config.get('metrics', {})
        if metrics:
            for key, value in metrics.items():
                if value is not None:
                    readme += f"- **{key}**: {value:.4f}\n"
        else:
            readme += "- No metrics recorded\n"

        readme += """
## Directory Structure

```
.
├── README.md           # This file
├── python/             # Python implementations
│   ├── analysis.py     # Standalone Python script
│   ├── analysis.ipynb  # Jupyter notebook
│   └── requirements.txt
├── r/                  # R implementations
│   ├── analysis.R      # Standalone R script
│   └── install_packages.R
"""

        if self.include_data:
            readme += """└── data/               # Data files
    ├── spectra.csv     # Spectral data
    ├── target.csv      # Target values
    └── wavelengths.csv # Wavelength information
"""
        else:
            readme += "```\n\n**Note**: Data files are not included in this bundle. "
            readme += "You'll need to provide your own data files.\n"

        readme += """
## Getting Started

### Python

1. Install required packages:
   ```bash
   pip install -r python/requirements.txt
   ```

2. Run the analysis:
   ```bash
   python python/analysis.py
   ```

3. Or open the Jupyter notebook:
   ```bash
   jupyter notebook python/analysis.ipynb
   ```

### R

1. Install required packages:
   ```R
   source("r/install_packages.R")
   ```

2. Run the analysis:
   ```R
   source("r/analysis.R")
   ```

## Data Files

"""

        if self.include_data:
            readme += f"""
The `data/` directory contains:

- `spectra.csv`: Spectral data matrix ({self.data_X.shape[0]} samples × {self.data_X.shape[1]} wavelengths)
- `target.csv`: Target values ({len(self.data_y)} values)
"""
            if self.wavelengths is not None:
                readme += f"- `wavelengths.csv`: Wavelength information ({len(self.wavelengths)} wavelengths)\n"

            readme += """
### Data Format

All data files are in CSV format with headers. The spectral data has samples as rows
and wavelengths as columns.
"""
        else:
            readme += """
Data files are not included in this export. To use the provided scripts:

1. Prepare your data in CSV format:
   - Spectral data: samples as rows, wavelengths as columns
   - Target data: one column with target values
   - Wavelengths (optional): one column with wavelength values

2. Update the file paths in the scripts to point to your data files.
"""

        readme += """
## Reproducibility

This export package contains everything needed to reproduce the analysis:

- Exact model configurations
- Preprocessing steps
- Cross-validation setup
- Training and evaluation code

The code is self-contained and can be run independently of Spectral Predict.

## Citation

If you use this analysis in a publication, please cite:

```
Spectral Predict - Automated NIR/IR Spectroscopy Modeling
Version: 1.0
https://github.com/yourusername/spectral-predict
```

## Support

For questions or issues with the exported code, please refer to the
Spectral Predict documentation or contact the maintainers.

---

Generated with Spectral Predict
"""

        return readme

    def _add_python_files(self, zipf: zipfile.ZipFile, bundle_name: str):
        """Add Python files to the bundle."""
        # Generate Python script - use relative path to data folder
        py_options = ExportOptions(
            include_visualization=False,
            include_prediction_template=True,
            format='script',
            include_data=False,  # Don't embed in script; use separate files
            data_path='../data/spectra.csv',  # Path relative to python/ folder
            target_column=self.config.get('target_name', 'target')
        )
        py_generator = CodeGenerator(self.config, py_options)
        py_script = py_generator.generate_script()
        zipf.writestr(f"{bundle_name}/python/analysis.py", py_script)

        # Generate Jupyter notebook - use relative path to data folder
        nb_options = ExportOptions(
            include_visualization=True,
            include_prediction_template=True,
            format='notebook',
            include_data=False,
            colab_ready=False,
            data_path='../data/spectra.csv',  # Path relative to python/ folder
            target_column=self.config.get('target_name', 'target')
        )
        nb_generator = CodeGenerator(self.config, nb_options)
        notebook = nb_generator.generate_notebook()
        zipf.writestr(f"{bundle_name}/python/analysis.ipynb", json.dumps(notebook, indent=2))

        # Generate requirements.txt
        requirements = self._generate_requirements_txt()
        zipf.writestr(f"{bundle_name}/python/requirements.txt", requirements)

    def _add_r_files(self, zipf: zipfile.ZipFile, bundle_name: str):
        """Add R files to the bundle."""
        # Generate R script
        r_generator = RCodeGenerator(
            model_config=self.config,
            include_data=False,  # Don't embed; use separate files
            data_X=self.data_X,
            data_y=self.data_y,
            wavelengths=self.wavelengths
        )
        r_script = r_generator.generate_script()
        zipf.writestr(f"{bundle_name}/r/analysis.R", r_script)

        # Generate install_packages.R
        install_script = self._generate_r_install_script()
        zipf.writestr(f"{bundle_name}/r/install_packages.R", install_script)

    def _add_data_files(self, zipf: zipfile.ZipFile, bundle_name: str):
        """Add data files to the bundle."""
        target_name = self.config.get('target_name', 'target')

        # Create column names from wavelengths
        if self.wavelengths is not None:
            col_names = [str(wl) for wl in self.wavelengths]
        else:
            col_names = [f"var_{i}" for i in range(self.data_X.shape[1])]

        # Create COMBINED data file (spectra + target) - this is what the scripts expect
        combined_df = pd.DataFrame(self.data_X, columns=col_names)
        combined_df[target_name] = self.data_y
        combined_csv = combined_df.to_csv(index=False)
        zipf.writestr(f"{bundle_name}/data/spectra.csv", combined_csv)

        # Also save separate files for flexibility
        # Spectral data only
        spectra_only_df = pd.DataFrame(self.data_X, columns=col_names)
        zipf.writestr(f"{bundle_name}/data/spectra_only.csv", spectra_only_df.to_csv(index=False))

        # Target data only
        target_df = pd.DataFrame({target_name: self.data_y})
        zipf.writestr(f"{bundle_name}/data/target.csv", target_df.to_csv(index=False))

        # Wavelengths (if available)
        if self.wavelengths is not None:
            wavelengths_df = pd.DataFrame({'wavelength': self.wavelengths})
            zipf.writestr(f"{bundle_name}/data/wavelengths.csv", wavelengths_df.to_csv(index=False))

    def _generate_requirements_txt(self) -> str:
        """Generate Python requirements.txt."""
        requirements = [
            "numpy>=1.19.0",
            "pandas>=1.1.0",
            "scikit-learn>=0.24.0",
            "scipy>=1.5.0",
        ]

        model_name = self.model_name.lower()
        if 'lightgbm' in model_name:
            requirements.append("lightgbm>=3.0.0")
        elif 'xgboost' in model_name:
            requirements.append("xgboost>=1.3.0")
        elif 'catboost' in model_name:
            requirements.append("catboost>=0.24.0")

        # Add optional packages
        requirements.extend([
            "",
            "# Optional packages",
            "matplotlib>=3.3.0  # For visualization",
            "jupyter>=1.0.0  # For notebook",
        ])

        return '\n'.join(requirements)

    def _generate_r_install_script(self) -> str:
        """Generate R package installation script."""
        r_generator = RCodeGenerator(self.config, include_data=False)
        packages = r_generator._get_required_packages()

        # Add base64enc for data decoding
        if 'base64enc' not in packages:
            packages.append('base64enc')
        if 'jsonlite' not in packages:
            packages.append('jsonlite')

        pkg_str = ', '.join(f'"{pkg}"' for pkg in packages)

        return f'''# Install required R packages
# Run this script once before running analysis.R

# List of required packages
packages <- c({pkg_str})

# Function to install packages if not already installed
install_if_missing <- function(pkg) {{
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {{
    cat("Installing package:", pkg, "\\n")
    install.packages(pkg, dependencies = TRUE)
  }} else {{
    cat("Package", pkg, "already installed\\n")
  }}
}}

# Install all required packages
for (pkg in packages) {{
  install_if_missing(pkg)
}}

cat("\\nAll required packages are installed!\\n")
'''


def create_export_bundle(
    model_config: Dict[str, Any],
    output_path: str,
    include_data: bool = True,
    data_X: Optional[np.ndarray] = None,
    data_y: Optional[np.ndarray] = None,
    wavelengths: Optional[np.ndarray] = None
) -> str:
    """
    Convenience function to create an export bundle.

    Parameters
    ----------
    model_config : dict
        Model configuration dictionary
    output_path : str
        Path for output ZIP file
    include_data : bool
        Include data files in bundle
    data_X : np.ndarray, optional
        Spectral data
    data_y : np.ndarray, optional
        Target values
    wavelengths : np.ndarray, optional
        Wavelength array

    Returns
    -------
    str
        Path to created ZIP file
    """
    bundle = ExportBundle(
        model_config=model_config,
        output_path=output_path,
        include_data=include_data,
        data_X=data_X,
        data_y=data_y,
        wavelengths=wavelengths
    )
    return bundle.create_bundle()
