"""
R export wrapper for reproducible analysis.

This module emits an R script that runs the Python export via reticulate to
ensure exact parity with GUI results. Native R generation has been removed.
"""

import base64
import gzip
from datetime import datetime
from typing import Dict, Any, Optional
import numpy as np


class RCodeGenerator:
    """
    Generate an R wrapper script that executes the Python export.

    Parameters
    ----------
    model_config : dict
        Model configuration dictionary (same as Python export).
    include_data : bool
        Whether to embed data in the Python export.
    data_X : np.ndarray, optional
        Spectral data.
    data_y : np.ndarray, optional
        Target values.
    wavelengths : np.ndarray, optional
        Wavelength array.
    """

    def __init__(
        self,
        model_config: Dict[str, Any],
        include_data: bool = False,
        data_X: Optional[np.ndarray] = None,
        data_y: Optional[np.ndarray] = None,
        wavelengths: Optional[np.ndarray] = None
    ):
        self.config = model_config
        self.include_data = include_data
        self.data_X = data_X
        self.data_y = data_y
        self.wavelengths = wavelengths

        self.model_name = model_config.get('model_name', 'Unknown')
        self.preprocessing = model_config.get('preprocessing', 'raw')
        self.task_type = model_config.get('task_type', 'regression')
        self.target_name = model_config.get('target_name', 'target')
        self.params = model_config.get('params', {})
        self.cv_folds = model_config.get('cv_folds', 5)

    def _encode_text(self, text: str) -> str:
        """Encode text to base64+gzip string."""
        data_bytes = text.encode('utf-8')
        compressed = gzip.compress(data_bytes, compresslevel=9)
        return base64.b64encode(compressed).decode('ascii')

    def _render_python_wrapper(self) -> str:
        """Render R wrapper that runs the Python export for exact parity."""
        from .code_generator import CodeGenerator, ExportOptions

        options = ExportOptions(
            include_visualization=False,
            include_prediction_template=True,
            format='script',
            include_data=self.include_data,
            data_X=self.data_X,
            data_y=self.data_y,
            wavelengths=self.wavelengths,
            data_path='your_data.csv',
            target_column=self.target_name
        )
        py_code = CodeGenerator(self.config, options).generate_script()
        py_encoded = self._encode_text(py_code)

        param_str = ', '.join(f"{k}: {v}" for k, v in self.params.items())
        if not param_str:
            param_str = 'default parameters'

        return f'''# ============================================================================
# Spectral Analysis in R (Python Wrapper)
# ============================================================================
# Generated by Spectral Predict on {datetime.now().strftime('%Y-%m-%d')}
#
# Model: {self.model_name}
# Preprocessing: {self.preprocessing}
# Task: {self.task_type}
# Parameters: {param_str}
# CV Folds: {self.cv_folds}
#
# NOTE:
# This wrapper runs the Python export via reticulate to ensure exact parity
# with GUI results. Native R generation has been removed.
# ============================================================================

# Install required packages (run once)
if (!require("reticulate", quietly = TRUE)) {{
  install.packages("reticulate")
}}
if (!require("base64enc", quietly = TRUE)) {{
  install.packages("base64enc")
}}

library(reticulate)
library(base64enc)

# OPTIONAL: point reticulate to your Python environment
# use_python("C:/Path/To/python.exe", required = TRUE)

# Decode embedded Python script
PY_CODE_ENCODED <- "{py_encoded}"
py_raw <- base64decode(PY_CODE_ENCODED)
py_code <- rawToChar(memDecompress(py_raw, type = "gzip"))

cat("Running Python export via reticulate...\\n")
py_run_string(py_code)
'''

    def generate_script(self) -> str:
        """Generate the R wrapper script."""
        return self._render_python_wrapper()

    def save_script(self, filepath: str) -> None:
        """Save R wrapper to file."""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(self.generate_script())


def generate_r_script_from_config(
    model_config: Dict[str, Any],
    include_data: bool = False,
    data_X: Optional[np.ndarray] = None,
    data_y: Optional[np.ndarray] = None,
    wavelengths: Optional[np.ndarray] = None
) -> str:
    """
    Convenience function to generate R wrapper script from model configuration.
    """
    generator = RCodeGenerator(
        model_config=model_config,
        include_data=include_data,
        data_X=data_X,
        data_y=data_y,
        wavelengths=wavelengths
    )
    return generator.generate_script()
