"""Report generation functions."""

from pathlib import Path
import pandas as pd


def write_markdown_report(target, df_ranked, out_dir):
    """
    Write a markdown report for the top-5 models.

    Parameters
    ----------
    target : str
        Target variable name
    df_ranked : pd.DataFrame
        Ranked results dataframe
    out_dir : str or Path
        Output directory

    Returns
    -------
    report_path : Path
        Path to generated report
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    report_path = out_dir / f"{target}.md"

    # Get top 5
    top5 = df_ranked.head(5)

    # Determine task type
    task_type = top5.iloc[0]["task_type"]

    # Build markdown content
    lines = [
        f"# Spectral Predict Report: {target}",
        "",
        f"**Task:** {task_type.capitalize()}",
        f"**Total models evaluated:** {len(df_ranked)}",
        "",
        "## Top 5 Models",
        "",
    ]

    for idx, row in top5.iterrows():
        lines.append(f"### Rank {row['Rank']}: {row['Model']} ({row['SubsetTag']})")
        lines.append("")
        lines.append(f"- **Composite Score:** {row['CompositeScore']:.4f}")
        lines.append(f"- **Model:** {row['Model']}")
        lines.append(f"- **Preprocess:** {row['Preprocess']}")

        if pd.notna(row["Deriv"]):
            lines.append(
                f"- **Derivative:** {int(row['Deriv'])} (window={int(row['Window'])}, poly={int(row['Poly'])})"
            )

        if pd.notna(row["LVs"]):
            lines.append(f"- **Latent Variables:** {int(row['LVs'])}")

        lines.append(f"- **Variables:** {int(row['n_vars'])} / {int(row['full_vars'])}")

        # Add metrics
        if task_type == "regression":
            lines.append(f"- **RMSE:** {row['RMSE']:.4f}")
            lines.append(f"- **R²:** {row['R2']:.4f}")
        else:
            lines.append(f"- **Accuracy:** {row['Accuracy']:.4f}")
            if pd.notna(row["ROC_AUC"]):
                lines.append(f"- **ROC AUC:** {row['ROC_AUC']:.4f}")

        lines.append("")

    # Add summary table
    lines.append("## Summary Table")
    lines.append("")

    # Select key columns for table
    if task_type == "regression":
        cols = [
            "Rank",
            "Model",
            "Preprocess",
            "SubsetTag",
            "LVs",
            "n_vars",
            "RMSE",
            "R2",
            "CompositeScore",
        ]
    else:
        cols = [
            "Rank",
            "Model",
            "Preprocess",
            "SubsetTag",
            "LVs",
            "n_vars",
            "Accuracy",
            "ROC_AUC",
            "CompositeScore",
        ]

    table_df = top5[cols].copy()

    # Format numeric columns
    for col in table_df.columns:
        if col in ["RMSE", "R2", "Accuracy", "ROC_AUC", "CompositeScore"]:
            table_df[col] = table_df[col].apply(lambda x: f"{x:.4f}" if pd.notna(x) else "N/A")
        elif col in ["LVs", "n_vars", "Rank"]:
            table_df[col] = table_df[col].apply(lambda x: f"{int(x)}" if pd.notna(x) else "N/A")

    lines.append(table_df.to_markdown(index=False))
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by Spectral Predict v0.1.0*")
    lines.append("")

    # Write to file
    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    return report_path
