"""Report generation functions."""

import re
from pathlib import Path
import pandas as pd


def write_markdown_report(target, df_ranked, out_dir):
    """
    Write a markdown report for the top-5 models.

    Parameters
    ----------
    target : str
        Target variable name
    df_ranked : pd.DataFrame
        Ranked results dataframe
    out_dir : str or Path
        Output directory

    Returns
    -------
    report_path : Path
        Path to generated report
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    safe_target = re.sub(r'[\\/:*?"<>|]', '_', target)
    report_path = out_dir / f"{safe_target}.md"

    # Handle empty results
    if len(df_ranked) == 0:
        lines = [
            f"# Spectral Predict Report: {target}",
            "",
            "**No models completed successfully.**",
            "",
            "Check the optimization logs for error messages.",
        ]
        with open(report_path, "w") as f:
            f.write("\n".join(lines))
        return report_path

    # Detect which score column exists (Bayesian uses 'Score', grid search uses 'CompositeScore')
    score_col = 'Score' if 'Score' in df_ranked.columns else 'CompositeScore'

    # Get top 5
    top5 = df_ranked.head(5)

    # Determine task type
    task_type = top5.iloc[0]["Task"]

    # Build markdown content
    lines = [
        f"# Spectral Predict Report: {target}",
        "",
        f"**Task:** {task_type.capitalize()}",
        f"**Total models evaluated:** {len(df_ranked)}",
        "",
        "## Top 5 Models",
        "",
    ]

    # Use itertuples() instead of iterrows() for better performance
    for row in top5.itertuples(index=False):
        lines.append(f"### Rank {row.Rank}: {row.Model} ({row.SubsetTag})")
        lines.append("")
        score_value = getattr(row, score_col)
        lines.append(f"- **Composite Score:** {score_value:.4f}")
        lines.append(f"- **Model:** {row.Model}")
        lines.append(f"- **Preprocess:** {row.Preprocess}")

        if pd.notna(row.Deriv):
            lines.append(
                f"- **Derivative:** {int(row.Deriv)} (window={int(row.Window)}, poly={int(row.Poly)})"
            )

        if pd.notna(row.LVs):
            lines.append(f"- **Latent Variables:** {int(row.LVs)}")

        lines.append(f"- **Variables:** {int(row.n_vars)} / {int(row.full_vars)}")

        # Add metrics
        if task_type == "regression":
            lines.append(f"- **RMSE:** {row.RMSE:.4f}")
            lines.append(f"- **R²:** {row.R2:.4f}")
        else:
            lines.append(f"- **Accuracy:** {row.Accuracy:.4f}")
            if pd.notna(row.ROC_AUC):
                lines.append(f"- **ROC AUC:** {row.ROC_AUC:.4f}")

        lines.append("")

    # Add summary table
    lines.append("## Summary Table")
    lines.append("")

    # Select key columns for table
    if task_type == "regression":
        cols = [
            "Rank",
            "Model",
            "Preprocess",
            "SubsetTag",
            "LVs",
            "n_vars",
            "RMSE",
            "R2",
            score_col,
        ]
    else:
        cols = [
            "Rank",
            "Model",
            "Preprocess",
            "SubsetTag",
            "LVs",
            "n_vars",
            "Accuracy",
            "ROC_AUC",
            score_col,
        ]

    table_df = top5[cols].copy()

    # Format numeric columns
    for col in table_df.columns:
        if col in ["RMSE", "R2", "Accuracy", "ROC_AUC", "CompositeScore", "Score"]:
            table_df[col] = table_df[col].apply(lambda x: f"{x:.4f}" if pd.notna(x) else "N/A")
        elif col in ["LVs", "n_vars", "Rank"]:
            table_df[col] = table_df[col].apply(lambda x: f"{int(x)}" if pd.notna(x) else "N/A")

    lines.append(table_df.to_markdown(index=False))
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by Spectral Predict v0.4.0*")
    lines.append("")

    # Write to file
    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    return report_path
