"""
Header and data loading templates for generated scripts.
"""

HEADER_TEMPLATE = '''"""
Spectral Analysis Script
========================
Generated by Spectral Predict v{dasp_version}
Date: {date}

Model: {model_name}
{model_details}
Preprocessing: {preprocessing}
{variable_selection_info}
Cross-validation: {cv_folds}-fold

This script reproduces the analysis performed in Spectral Predict.
It is standalone and requires only standard scientific Python libraries.

Required packages: numpy, pandas, sklearn, scipy{extra_packages}
"""

import numpy as np
import pandas as pd
{imports}
'''

DATA_LOADING_TEMPLATE = '''
# =============================================================================
# DATA LOADING
# =============================================================================

# Load your spectral data
# Expected format: CSV with wavelength columns and target column
data = pd.read_csv("{data_path}")  # <-- Replace with your data file path

# Identify spectral columns (columns with numeric names representing wavelengths)
# Adjust this logic if your column naming convention is different
wavelength_cols = [c for c in data.columns
                   if c.replace('.', '').replace('-', '').replace('+', '').isdigit()
                   or (c.replace('.', '').replace('-', '').replace('+', '')[0].isdigit())]

# If wavelength detection fails, you can manually specify columns:
# wavelength_cols = data.columns[10:].tolist()  # Example: columns 10 onwards

X = data[wavelength_cols].values
y = data["{target_column}"].values  # <-- Replace with your target column name
wavelengths = np.array([float(c) for c in wavelength_cols])

print(f"Loaded {{X.shape[0]}} samples with {{X.shape[1]}} wavelengths")
print(f"Wavelength range: {{wavelengths.min():.1f}} - {{wavelengths.max():.1f}} nm")
print(f"Target ('{target_column}'): min={{y.min():.3f}}, max={{y.max():.3f}}, mean={{y.mean():.3f}}")
'''

DATA_LOADING_CLASSIFICATION_TEMPLATE = '''
# =============================================================================
# DATA LOADING
# =============================================================================

# Load your spectral data
# Expected format: CSV with wavelength columns and target column
data = pd.read_csv("{data_path}")  # <-- Replace with your data file path

# Identify spectral columns (columns with numeric names representing wavelengths)
wavelength_cols = [c for c in data.columns
                   if c.replace('.', '').replace('-', '').replace('+', '').isdigit()
                   or (c.replace('.', '').replace('-', '').replace('+', '')[0].isdigit())]

X = data[wavelength_cols].values
y = data["{target_column}"].values  # <-- Replace with your target column name
wavelengths = np.array([float(c) for c in wavelength_cols])

# For classification, encode labels if they are strings
from sklearn.preprocessing import LabelEncoder
if not pd.api.types.is_numeric_dtype(y.dtype):
    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y)
    class_names = label_encoder.classes_
    print(f"Classes: {{class_names}}")
else:
    class_names = np.unique(y)

print(f"Loaded {{X.shape[0]}} samples with {{X.shape[1]}} wavelengths")
print(f"Wavelength range: {{wavelengths.min():.1f}} - {{wavelengths.max():.1f}} nm")
print(f"Class distribution: {{dict(zip(*np.unique(y, return_counts=True)))}}")
'''

DATA_LOADING_ONE_CLASS_TEMPLATE = '''
# =============================================================================
# DATA LOADING (One-Class)
# =============================================================================

data = pd.read_csv("{data_path}")  # <-- Replace with your data file path

wavelength_cols = [c for c in data.columns
                   if c.replace('.', '').replace('-', '').replace('+', '').isdigit()
                   or (c.replace('.', '').replace('-', '').replace('+', '')[0].isdigit())]

X = data[wavelength_cols].values
wavelengths = np.array([float(c) for c in wavelength_cols])

class_col = data["{target_column}"].values
y_oc = np.where(np.array([str(v).strip() for v in class_col]) == "{inlier_class_label}", 1, -1)
inlier_indices = np.where(y_oc == 1)[0]
outlier_indices = np.where(y_oc == -1)[0]

print(f"Loaded {{X.shape[0]}} samples with {{X.shape[1]}} wavelengths")
print(f"Wavelength range: {{wavelengths.min():.1f}} - {{wavelengths.max():.1f}} nm")
print(f"Inlier class: '{inlier_class_label}' -> {{len(inlier_indices)}} inliers, {{len(outlier_indices)}} outliers")
'''
